[package]
name = "hdr-auto"
version = "0.1.2"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = [
    "errhandlingapi",
    "handleapi",
    "libloaderapi",
    "processthreadsapi",
    "shellapi",
    "synchapi",
    "tlhelp32",
    "unknwnbase",
    "winerror",
    "winbase",
    "winnt",
    "winreg",
    "winuser",
    "wingdi",
] }

[build-dependencies]
winres = "0.1"
